# Generated by Django 3.2.9 on 2021-12-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweetId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=4000)),
                ('htmlElement', models.CharField(max_length=1000)),
                ('classPredicted', models.IntegerField()),
            ],
        ),
    ]
