# Generated by Django 3.2.9 on 2021-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepyStreamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='classPredicted',
            field=models.IntegerField(null=True),
        ),
    ]
