# Generated by Django 3.2.9 on 2021-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepyStreamer', '0002_alter_tweet_classpredicted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='classPredicted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
